name = "GeodeticOps"
uuid = "d87b55ab-7a67-4b26-bb25-1f22980f9a10"
version = "0.1.0"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
